import { AuthProvider } from "@/Provider/NextAuthProvider";
import "../globals.css";
import { Inter } from "next/font/google";
import { ToasterProvider } from "@/components/ToasterProvider";
import TopBar from "@/components/layout/TopBar";
import LeftSideBar from "@/components/layout/LeftSideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToasterProvider />
          <div className="flex max-lg:flex-col text-[#616161] ">
            <TopBar />
            <LeftSideBar />
            <div className="flex-1">{children}</div>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
